### ISSUE TITLE
Packagist registration

### ISSUE THREAD

**Issue by Maxwell2022** [rase-/socket.io-php-emitter#3]
You should register your package to https://packagist.org, so we can download it from composer

**Comment by rauchg** [comment]
+1

**Comment by rauchg** [comment]
@Maxwell2022 do you think it would be best to register it as `socket.io-emitter` there?

**Comment by rauchg** [comment]
(i.e.: no `-php`)

**Comment by Maxwell2022** [comment]
I don't know. It doesn't really matter as long as I can download it :)

**Comment by rase-** [comment]
Thanks @Maxwell2022 and @guille! Published [here](https://packagist.org/packages/rase/socket.io-emitter) as `socket.io-emitter`.
