### ISSUE TITLE
Use Emitter.php instead of emitter.php

### ISSUE THREAD

**Issue by radzserg** [rase-/socket.io-php-emitter#6]
According to psr4 
`All class names MUST be referenced in a case-sensitive fashion.`

**Comment by steelbrain** [comment]
[This pull request](https://github.com/rase-/socket.io-php-emitter/pull/5) resolves this issue

**Comment by rase-** [comment]
Thanks for reporting. Fixed by https://github.com/rase-/socket.io-php-emitter/commit/27742a9c3843da99c55c3505bd6244cd52c18518
